### ISSUE TITLE
Operator description to restrictive

### ISSUE THREAD

**Issue by dbrattli** [MainRo/dooble#7]
* dooble version:  0.6.0
* Python version: 3.7
* Operating System: OS X

### Description

This is a really great project. Trying to use Dooble with F# and the regexp for the description of the operator do not allow chars like `-`, `{`and `}`. But it would be nice to also have e.g `/`, `$`, `=`, `%` to support other programming languages and their ways of writing lambda expressions. 

### What I Did

```
    .. marble::
        :alt: map

        ---1---2---3---4--->
        [ map (fun i -> i*2) ]
        ---2---4---6---8--->
```

Traceback

```
Exception occurred:
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 453, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedToken: (2:14) expecting ']' :
[ map (fun i -> i*2) ]
             ^
```

**Comment by MainRo** [comment]
Yes, I chose to restrict the syntax to the minimal requirements for python initially to ensure the is no conflict in the syntax. Great to see that dooble may be used in other projects!
